// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCecxpIaUtcN1WyvJl9KzUHfRPJc9GY5f8',
    appId: '1:517071692648:web:b859f709dafa176d792cdd',
    messagingSenderId: '517071692648',
    projectId: 'fir-frontend-b8b97',
    authDomain: 'fir-frontend-b8b97.firebaseapp.com',
    storageBucket: 'fir-frontend-b8b97.firebasestorage.app',
    measurementId: 'G-00MNVNMFDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoY8SlmDbHMkeva4KPzE1QLeqn8ZtXEBY',
    appId: '1:517071692648:android:b9403c17039214d0792cdd',
    messagingSenderId: '517071692648',
    projectId: 'fir-frontend-b8b97',
    storageBucket: 'fir-frontend-b8b97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt2RB1f1IXU_WUnT_X9FK2iEc_-9tAypc',
    appId: '1:517071692648:ios:468c0ffc0459ba8c792cdd',
    messagingSenderId: '517071692648',
    projectId: 'fir-frontend-b8b97',
    storageBucket: 'fir-frontend-b8b97.firebasestorage.app',
    iosClientId: '517071692648-ic1uk8spbufsobjecq0uqo9plo7037pb.apps.googleusercontent.com',
    iosBundleId: 'com.example.needsBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt2RB1f1IXU_WUnT_X9FK2iEc_-9tAypc',
    appId: '1:517071692648:ios:468c0ffc0459ba8c792cdd',
    messagingSenderId: '517071692648',
    projectId: 'fir-frontend-b8b97',
    storageBucket: 'fir-frontend-b8b97.firebasestorage.app',
    iosClientId: '517071692648-ic1uk8spbufsobjecq0uqo9plo7037pb.apps.googleusercontent.com',
    iosBundleId: 'com.example.needsBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCecxpIaUtcN1WyvJl9KzUHfRPJc9GY5f8',
    appId: '1:517071692648:web:e5dd6f9b5239a202792cdd',
    messagingSenderId: '517071692648',
    projectId: 'fir-frontend-b8b97',
    authDomain: 'fir-frontend-b8b97.firebaseapp.com',
    storageBucket: 'fir-frontend-b8b97.firebasestorage.app',
    measurementId: 'G-BEX116LKWK',
  );
}
