// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZb8fps_Ic1a3ePiENWMACzTPSTjOPpW4',
    appId: '1:734731390097:web:86f0f869eedb3ff8970330',
    messagingSenderId: '734731390097',
    projectId: 'thunder-3ba41',
    authDomain: 'thunder-3ba41.firebaseapp.com',
    storageBucket: 'thunder-3ba41.firebasestorage.app',
    measurementId: 'G-SKRNXFBY87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9eqs7TE--g-5CxGvc4862Y0eVHHZuReU',
    appId: '1:734731390097:android:df5c1a93cf0d5d29970330',
    messagingSenderId: '734731390097',
    projectId: 'thunder-3ba41',
    storageBucket: 'thunder-3ba41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5QYEoFZ0Wih-UskcleJmHZ9z_lY1pPbs',
    appId: '1:734731390097:ios:a6a69f8fec53405d970330',
    messagingSenderId: '734731390097',
    projectId: 'thunder-3ba41',
    storageBucket: 'thunder-3ba41.firebasestorage.app',
    iosBundleId: 'com.example.needsBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5QYEoFZ0Wih-UskcleJmHZ9z_lY1pPbs',
    appId: '1:734731390097:ios:a6a69f8fec53405d970330',
    messagingSenderId: '734731390097',
    projectId: 'thunder-3ba41',
    storageBucket: 'thunder-3ba41.firebasestorage.app',
    iosBundleId: 'com.example.needsBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZb8fps_Ic1a3ePiENWMACzTPSTjOPpW4',
    appId: '1:734731390097:web:98592232c5d0ca3f970330',
    messagingSenderId: '734731390097',
    projectId: 'thunder-3ba41',
    authDomain: 'thunder-3ba41.firebaseapp.com',
    storageBucket: 'thunder-3ba41.firebasestorage.app',
    measurementId: 'G-WEZMX8HF1X',
  );
}
