import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';
import '../../models/need.dart';
import '../../services/firebase_need_service.dart';
import '../../providers/app_providers.dart';

class AddNeedScreen extends StatefulWidget {
  const AddNeedScreen({super.key});

  @override
  State<AddNeedScreen> createState() => _AddNeedScreenState();
}

class _AddNeedScreenState extends State<AddNeedScreen> {
  final _formKey = GlobalKey<FormState>();
  final _descCtrl = TextEditingController();
  final _locationCtrl = TextEditingController();
  final _peopleCtrl = TextEditingController(text: '0');
  NeedCategory _category = NeedCategory.food;
  UrgencyLevel _urgency = UrgencyLevel.medium;

  @override
  void dispose() {
    _descCtrl.dispose();
    _locationCtrl.dispose();
    _peopleCtrl.dispose();
    super.dispose();
  }

  Future<void> _submitNeed() async {
    if (!_formKey.currentState!.validate()) return;

    final auth = context.read<AuthProvider>();
    final user = auth.currentUser;
    if (user == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please log in')));
      return;
    }

    final need = Need(
      id: '', // Generated by Firestore
      description: _descCtrl.text,
      category: _category,
      urgencyLevel: _urgency,
      urgencyScore: _urgency == UrgencyLevel.critical ? 9.0 : _urgency == UrgencyLevel.medium ? 5.0 : 2.0,
      status: NeedStatus.reported,
      location: _locationCtrl.text,
      submittedBy: user.id,
      peopleAffected: int.tryParse(_peopleCtrl.text) ?? 0,
      timestamp: DateTime.now(),
    );

    final needsProvider = context.read<NeedsProvider>();
    await needsProvider.submitNeed(need);
    
    if (needsProvider.error == null && mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Need posted successfully!')),
      );
      context.pop();
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Failed to post need. Try again.')),
      );
    }
  }

  static String _categoryLabel(NeedCategory c) {
    switch (c) {
      case NeedCategory.food: return 'Food';
      case NeedCategory.medical: return 'Medical';
      case NeedCategory.shelter: return 'Shelter';
      case NeedCategory.education: return 'Education';
      case NeedCategory.sanitation: return 'Sanitation';
      case NeedCategory.other: return 'Other';
    }
  }

  static String _urgencyLabel(UrgencyLevel u) {
    switch (u) {
      case UrgencyLevel.low: return 'Low';
      case UrgencyLevel.medium: return 'Medium';
      case UrgencyLevel.critical: return 'Critical';
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Add New Need'),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => context.pop(),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              TextFormField(
                controller: _descCtrl,
                maxLines: 3,
                decoration: const InputDecoration(
                  labelText: 'Description *',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.description_outlined),
                  alignLabelWithHint: true,
                ),
                validator: (value) => value?.isEmpty ?? true ? 'Description is required' : null,
              ),
              const SizedBox(height: 16),
              DropdownButtonFormField<NeedCategory>(
                value: _category,
                decoration: const InputDecoration(
                  labelText: 'Category',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.category_outlined),
                ),
                items: NeedCategory.values.map((c) => DropdownMenuItem(
                  value: c,
                  child: Text(_categoryLabel(c)),
                )).toList(),
                onChanged: (value) => setState(() => _category = value!),
              ),
              const SizedBox(height: 16),
              DropdownButtonFormField<UrgencyLevel>(
                value: _urgency,
                decoration: const InputDecoration(
                  labelText: 'Urgency',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.warning_outlined),
                ),
                items: UrgencyLevel.values.map((u) => DropdownMenuItem(
                  value: u,
                  child: Text(_urgencyLabel(u)),
                )).toList(),
                onChanged: (value) => setState(() => _urgency = value!),
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _locationCtrl,
                decoration: const InputDecoration(
                  labelText: 'Location *',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.location_on_outlined),
                ),
                validator: (value) => value?.isEmpty ?? true ? 'Location is required' : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _peopleCtrl,
                keyboardType: TextInputType.number,
                decoration: const InputDecoration(
                  labelText: 'People Affected',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.people_outlined),
                ),
              ),
              const SizedBox(height: 32),
              ElevatedButton.icon(
                onPressed: _submitNeed,
                icon: const Icon(Icons.send),
                label: const Text('Post Need'),
                style: ElevatedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 16),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
